### PR TITLE
Handle conditional fields better

### LINKED ISSUE #618: Symptoms should clear if changing symptom status
To reproduce:
- Click symptomatic for symptom status
- Add a symptom
- Click unknown for symptom status

Issues:
- Green checkmark is still shown in table of contents
- The symptom is added to the datalist

### PR DESCRIPTION
**Pull request by allysonjp715**
- Do not store results when conditions are not met
- Do not show green checkmark when conditions are not met

Fixes #618

### CODE REVIEW

File: verification/curator-service/ui/src/components/CaseForm.tsx [hunk 1]
```diff
@@ -405,7 +409,11 @@ class CaseForm extends React.Component<Props, CaseFormState> {
                 }),
             symptoms: {
                 status: unknownToUndefined(values.symptomsStatus),
-                values: values.symptoms,
+                values:
+                    values.symptomsStatus === 'Symptomatic' ||
```
Comment (attwad) [inline verification/curator-service/ui/src/components/CaseForm.tsx:413]: Am i understanding correctly that you could select Symptomatic, then select symptoms, then remove the Symptomatic selection but symptoms would still be sent? If this wasn't happening I'm not sure what we're getting by doing this.

Comment (allysonjp715) [reply verification/curator-service/ui/src/components/CaseForm.tsx:413]: Yes that was happening. A big bug!
