### PR TITLE
fix query at runtime to support mistyped keyword searches

### LINKED ISSUE #1156: Female results appear in male search
**Describe the bug**
https://curator.ghdsi.org/cases showed a completely white screen after running a search query

**To Reproduce**

1. Go to the line list view
2. Searched - gender: male
3. 2 results female results appear 
 

**Expected behavior**
Search male result displayed.

**Screenshots**

**Environment (please complete the following information):**

### PR DESCRIPTION
**Pull request by attwad**
Fixes #1156

### CODE REVIEW

File: data-serving/data-service/src/util/search.ts [hunk 1]
```diff
@@ -31,6 +31,10 @@ const keywords = new Map<string, string>([
 
 export default function parseSearchQuery(q: string): ParsedSearch {
     q = q.trim();
+    // parse() doesn't handle most-likely mistyped queries like
+    // "curator: foo@bar.com" (with a space after the semicolon).
+    // Change the query here to account for that.
```
Comment (allysonjp715) [inline data-serving/data-service/src/util/search.ts:36]: Nit: could you write in the comment that this is taking out the whitespace between the : and the search query? So readers don't have to parse the regex :)

**Review by allysonjp715 — APPROVED** [review]
Great, thanks!

File: data-serving/data-service/src/util/search.ts (hunk 1 above)
Comment (attwad) [reply data-serving/data-service/src/util/search.ts]: done
