### PR TITLE
Fix UX of selecting Unknown fields

### LINKED ISSUE #444: UX for unknown fields
Selecting Unknown makes no change to the field, just remains blank.
UX to confirm expected functionality and UX when selected.
See attached design currently.

Screen Shot 2020-07-06 at 2 10 18 PM

### PR DESCRIPTION
**Pull request by allysonjp715**
Fixes #444

### CODE REVIEW

File: verification/curator-service/ui/src/components/new-case-form-fields/Symptoms.tsx [hunk 1]
```diff
@@ -11,7 +11,7 @@ import { useFormikContext } from 'formik';
 
 // TODO: get values from DB
```
Comment (attwad) [inline verification/curator-service/ui/src/components/new-case-form-fields/Symptoms.tsx:12]: nit but should we really be getting those 3 from the DB? I don't think so.

File: verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx [hunk 2]
```diff
@@ -33,10 +33,10 @@ const useStyles = makeStyles(() => ({
     },
 }));
 
-const hasTravelledValues = [undefined, 'Yes', 'No'];
+const hasTravelledValues = ['Unknown', 'Yes', 'No'];
 
 // TODO: get values from DB.
```
Comment (attwad) [inline verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx:38]: ditto

File: verification/curator-service/ui/src/components/new-case-form-fields/Symptoms.tsx (hunk 1 above)
Comment (allysonjp715) [reply verification/curator-service/ui/src/components/new-case-form-fields/Symptoms.tsx:12]: If we are going to verify the field is one of these 3 values in the backend, it would be nice to only have the values defined in one location eventually. Agree it's not high priority.

File: verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx (hunk 2 above)
Comment (allysonjp715) [reply verification/curator-service/ui/src/components/new-case-form-fields/TravelHistory.tsx:38]: ditto :)
