### PR TITLE
Sort uploads by most recent first

### LINKED ISSUE #1116: Change upload list ordering from latest date to oldest
**Describe the bug**
Change upload list ordering from latest date to oldest

Currently set from oldest to newest so need to scroll through to end to check out the latest uploads for verification
Screen Shot 2020-09-17 at 1 03 24 PM

### PR DESCRIPTION
**Pull request by allysonjp715**
For #1116

### CODE REVIEW

File: verification/curator-service/api/src/controllers/uploads.ts [hunk 1]
```diff
@@ -115,6 +115,7 @@ export default class UploadsController {
                             upload: '$uploads',
                         },
                     },
+                    { $sort: { 'upload.created': -1 } },
```
Comment (axmb) [inline verification/curator-service/api/src/controllers/uploads.ts:118]: This is probably cool if `created` has timestamp resolution, but we probably want an explicit secondary sort otherwise.

**Review by axmb — APPROVED** [review]

File: verification/curator-service/api/src/controllers/uploads.ts (hunk 1 above)
Comment (attwad) [reply verification/curator-service/api/src/controllers/uploads.ts:118]: you'll need an index as well for sorting, look at the schema for cases for an example (it should have a sort-related comment on it)

Comment (attwad) [reply verification/curator-service/api/src/controllers/uploads.ts:118]: I meant this:
https://github.com/globaldothealth/list/blob/main/data-serving/data-service/schemas/cases.indexes.json#L162

but note that it's not going to be an issue unless we reach a significant amount of uploads to go through so probably find to do in another PR (we started seeing OOMs due to sorting without an index at around 170K cases).

Comment (allysonjp715) [reply verification/curator-service/api/src/controllers/uploads.ts:118]: Got it. I'll add the index in a separate PR since it will take some figuring out how to set up the first index for the curator-service (and I want to get the build fixes in).  

In terms of a secondary sort, I think it's okay to default to the order that was happening before we added this (I believe based on order added to the DB). WDYT?

Comment (axmb) [reply verification/curator-service/api/src/controllers/uploads.ts:118]: I'd say one of two things:

1. If `created` is a time (and not just a date), show the HH:MM and no need for a secondary sort.
2. If `created` is a date, like it's displayed, we should probably secondary sort by the source name. Just so it's easier to find the relevant upload and the table appears to be organized.

Comment (allysonjp715) [reply verification/curator-service/api/src/controllers/uploads.ts]: Added secondary sort on source name

**Comment by z023** [comment]
Uploads still listed as oldest first. Where is this issue at?

**Comment by allysonjp715** [comment]
> Uploads still listed as oldest first. Where is this issue at?

We just hadn't pushed yet. I just pushed dev and you can now see the correct ordering there.

**Comment by z023** [comment]
I'm currently seeing each uploads page is sorted by most recent rather than the whole uploads list being sorted by most recent.

**Comment by allysonjp715** [comment]
> I'm currently seeing each uploads page is sorted by most recent rather than the whole uploads list being sorted by most recent.

Indeed, silly mistake, will sent PR.

**Comment by z023** [comment]
Still seeing the same issue.

**Comment by allysonjp715** [comment]
Hm this doesn't seem fixed even after a push. Will reopen #1116

**Comment by z023** [comment]
Any progress with this?

**Comment by allysonjp715** [comment]
#1303

**Comment by allysonjp715** [comment]
Fix has pushed to prod now and it lgtm.
